// Dados do jogo - Verdade ou Desafio Desbravadores
const gameData = {
    amigo: {
        name: 'Amigo',
        displayName: 'Classe Amigo',
        verdades: [
            'Quantos anos você tem atualmente e como comprova que atende ao requisito mínimo de 10 anos da Classe Amigo?',
            'Com quantos anos você tinha quando passou a atender ao requisito de idade mínima para a Classe Amigo?',
            'Por que a Classe Amigo exige idade mínima de 10 anos para participação?',
            'O que você já consegue fazer hoje, como desbravador, que talvez não conseguiria antes dessa idade?',
            'Como a idade mínima ajuda no aprendizado e na responsabilidade dentro do Clube?',
            'O que significa, na prática, cumprir o requisito de ser um membro ativo do Clube de Desbravadores?',
            'Quais tipos de atividades mostram que você é um membro ativo do Clube?',
            'Por que apenas estar inscrito não é suficiente para cumprir esse requisito?',
            'O que acontece com o aprendizado do desbravador quando ele não participa ativamente?',
            'Qual atitude sua demonstra claramente que você cumpre o requisito de membro ativo?',
            'Recite o Voto do Desbravador.',
            'Recite a Lei do Desbravador.',
            'Explique, com suas palavras, o significado do Voto do Desbravador.',
            'Qual item da Lei do Desbravador você acha mais difícil de praticar e por quê?',
            'Como o Voto e a Lei orientam o comportamento diário do desbravador?',
            'Qual é o nome do livro do Clube de Leitura do ano em curso que você leu para cumprir este requisito?',
            'Qual é o tema ou a história principal desse livro?',
            'Qual parte do livro do Clube de Leitura mais chamou sua atenção?',
            'Que lição principal você aprendeu ao cumprir o requisito de leitura desse livro?',
            'Por que a leitura faz parte da formação do desbravador?',
            'Qual é a mensagem principal do livro Vaso de Barro, lido para cumprir este requisito?',
            'O que significa ser um vaso nas mãos de Deus, segundo o livro Vaso de Barro?',
            'Qual ensinamento do livro Vaso de Barro mais te marcou?',
            'O que o livro Vaso de Barro ensina sobre falhas humanas e restauração?',
            'Como a leitura de Vaso de Barro contribuiu para seu crescimento espiritual?',
            'Por que participar ativamente da classe bíblica é um requisito da Classe Amigo?',
            'Cite um ensinamento aprendido na classe bíblica do Clube.',
            'Como a classe bíblica ajuda o desbravador a conhecer melhor a Bíblia?',
            'Qual história ou personagem bíblico você aprendeu estudando na classe bíblica?',
            'De que forma participar da classe bíblica fortalece sua vida espiritual?',
            'O que Deus criou no primeiro dia da Criação, conforme o relato bíblico exigido neste requisito?',
            'O que Deus criou no segundo e no terceiro dia da Criação?',
            'O que foi criado no quarto dia e qual a função do sol, da lua e das estrelas?',
            'Em que dia Deus criou os seres humanos e o que isso demonstra sobre o cuidado de Deus?',
            'Por que Deus descansou no sétimo dia e o que esse dia representa?',
            'Cite pelo menos cinco das dez pragas que caíram sobre o Egito, conforme exige este requisito.',
            'Por que Deus enviou as pragas sobre o Egito?',
            'Quem era o líder do Egito durante as pragas e qual foi sua atitude?',
            'Qual era o objetivo de Deus ao libertar o povo de Israel por meio das pragas?',
            'O que as pragas ensinam sobre obediência e consequências?',
            'Quem foi o pai das doze tribos de Israel, conforme o requisito estudado?',
            'Cite o nome de pelo menos seis das doze tribos de Israel.',
            'Por que as tribos de Israel eram importantes para a organização do povo de Deus?',
            'O que a divisão em tribos ensina sobre família e identidade?',
            'Como Deus usou as tribos para cumprir Seus planos?',
            'Quantos livros formam o Antigo Testamento, conforme exige este requisito?',
            'Cite cinco livros do Antigo Testamento em ordem correta.',
            'Qual é o primeiro livro do Antigo Testamento e do que ele trata?',
            'Qual é o último livro do Antigo Testamento?',
            'Por que é importante saber localizar qualquer livro do Antigo Testamento na Bíblia?',
            'Recite João 3:16, conforme exigido neste requisito.',
            'Explique o ensinamento principal de Efésios 6:1–3.',
            'O que II Timóteo 3:16 ensina sobre a origem da Bíblia?',
            'Qual é a mensagem principal do Salmo 1?',
            'Qual desses versos bíblicos estudados mais falou ao seu coração e por quê?',
            'Cite um personagem bíblico estudado na leitura de Gênesis ou Êxodo e explique quem ele foi.',
            'O que você aprendeu com a história de Noé, conforme a leitura bíblica exigida?',
            'Qual foi a missão de Moisés no livro de Êxodo?',
            'Cite um ensinamento importante aprendido na leitura bíblica de Gênesis e Êxodo.',
            'Por que a leitura regular da Bíblia é importante para a vida espiritual do desbravador?',
            'Para cumprir o requisito de serviço comunitário, quem foi a pessoa ou grupo da comunidade que você ajudou?',
            'Qual das atividades previstas neste requisito você realizou?',
            'Quanto tempo você dedicou a esse serviço comunitário?',
            'Por que essa pessoa ou grupo precisava de ajuda naquele momento?',
            'O que você aprendeu pessoalmente ao cumprir o requisito de servir alguém da comunidade?',
            'Segundo a redação que você escreveu, o que significa ser um bom cidadão dentro do lar?',
            'Segundo sua redação, o que significa ser um bom cidadão na escola?',
            'Por que respeitar regras e autoridades faz parte de ser um bom cidadão?',
            'Como as atitudes de um desbravador podem influenciar positivamente outras pessoas no lar e na escola?',
            'Cite um exemplo apresentado na sua redação que demonstre boa cidadania.',
            'Cite dez qualidades de um bom amigo, conforme exige este requisito.',
            'O que significa a Regra Áurea de Mateus 7:12 e como ela se aplica às amizades?',
            'Por que a amizade é importante para o desenvolvimento do desbravador?',
            'Cite atitudes que podem prejudicar uma amizade.',
            'Como Jesus demonstrou a Regra Áurea em Seu relacionamento com as pessoas?',
            'Qual é o nome oficial do Hino Nacional do Brasil?',
            'Quem escreveu a letra do Hino Nacional Brasileiro?',
            'Quem compôs a música do Hino Nacional Brasileiro?',
            'Qual é a importância do Hino Nacional para o país?',
            'Em quais situações o Hino Nacional deve ser cantado ou respeitado?',
            'Qual especialidade de Saúde e Aptidão Física você escolheu concluir para a Classe Amigo?',
            'Por que essa especialidade é importante para o cuidado do corpo?',
            'Cite dois aprendizados principais obtidos ao concluir essa especialidade.',
            'Quais regras de segurança estão relacionadas a essa especialidade?',
            'Como essa especialidade pode ajudar você no dia a dia?',
            'Quais princípios de temperança Daniel defendeu, conforme Daniel capítulo 1?',
            'Por que Daniel decidiu não se contaminar com a comida do rei?',
            'O que significa temperança dentro do estilo de vida cristão?',
            'Como o exemplo de Daniel se relaciona com saúde hoje?',
            'Explique, com suas palavras, o significado de Daniel 1:8.',
            'Quais são os princípios básicos de uma dieta saudável aprendidos neste requisito?',
            'Cite os grupos básicos de alimentos.',
            'Por que é importante ter uma alimentação equilibrada?',
            'Quais problemas podem surgir com uma alimentação inadequada?',
            'Como a alimentação influencia a saúde física e mental?',
            'O que precisa ser planejado antes de uma caminhada de 5 km?',
            'Quem participa do planejamento de uma caminhada?',
            'Por que a segurança é importante durante uma caminhada?',
            'Que cuidados devem ser tomados durante uma caminhada?',
            'O que pode dar errado se não houver planejamento adequado?',
            'Qual especialidade de Estudo da Natureza você escolheu concluir para a Classe Amigo?',
            'Quais são as principais características estudadas nessa especialidade?',
            'Cite dois aprendizados importantes obtidos ao completar essa especialidade.',
            'Por que o estudo da natureza é importante para compreender a criação de Deus?',
            'Como esse conhecimento ajuda no cuidado com a natureza ou com os animais?',
            'Quais são as formas aprendidas neste requisito para purificar a água?',
            'Por que a purificação da água é importante para a saúde humana?',
            'O que Jesus quis ensinar ao se apresentar como a Água da Vida?',
            'Explique a relação entre água limpa para o corpo e Jesus como água para a vida espiritual.',
            'Por que esse requisito une conhecimento prático da natureza com ensinamento espiritual?',
            'Quantos tipos diferentes de barracas você aprendeu a montar neste requisito?',
            'Por que é importante montar barracas apenas em locais apropriados?',
            'Quais cuidados devem ser tomados antes de montar uma barraca?',
            'Cite dificuldades comuns ao montar uma barraca e como evitá-las.',
            'Como esse aprendizado ajuda em acampamentos e atividades ao ar livre?',
            'Segundo o requisito de Arte de Acampar, por que é importante cuidar corretamente de uma corda?',
            'Quais cuidados devem ser tomados para conservar uma corda em boas condições?',
            'Qual a finalidade prática dos nós aprendidos neste requisito?',
            'Por que aprender diferentes tipos de nós é importante em atividades de acampamento?',
            'Por que o uso correto dos nós aumenta a segurança no acampamento?',
            'O que você aprendeu ao concluir a especialidade de Acampamento I?',
            'Quais conhecimentos básicos de acampamento são ensinados nessa especialidade?',
            'Por que a especialidade de Acampamento I é importante para a segurança?',
            'Cite dois aprendizados práticos que você considera mais importantes dessa especialidade.',
            'Como esse aprendizado contribui para um acampamento organizado e seguro?',
            'Cite dez regras para uma caminhada segura, conforme exige este requisito.',
            'Por que seguir regras em uma caminhada é fundamental para a segurança do grupo?',
            'O que uma pessoa deve fazer ao perceber que está perdida durante uma caminhada?',
            'Quais erros comuns devem ser evitados quando alguém se perde na trilha?',
            'Como o preparo prévio reduz riscos durante caminhadas?',
            'Para que servem os sinais de pista aprendidos neste requisito?',
            'Quantos sinais, no mínimo, uma pista deve ter para cumprir este requisito?',
            'Por que os sinais de pista devem ser claros e padronizados?',
            'Explique a importância de preparar uma pista que possa ser seguida por outras pessoas.',
            'Como os sinais de pista ajudam na orientação em ambientes naturais?',
            'Qual especialidade de Artes e Habilidades Manuais você escolheu completar para cumprir este requisito?',
            'Explique qual era o objetivo principal dessa especialidade de Artes e Habilidades Manuais.',
            'Cite pelo menos duas habilidades ou técnicas aprendidas ao cumprir esse requisito.',
            'Qual foi a parte mais difícil dessa especialidade e por quê?',
            'Explique como essa especialidade contribui para o desenvolvimento da criatividade, paciência e atenção aos detalhes.',
        ],
        desafios: [
            'Conte para o grupo como foi começar no Clube após atingir a idade mínima exigida.',
            'Explique para um colega mais novo por que ainda não é possível fazer a Classe Amigo antes dos 10 anos.',
            'Diga uma responsabilidade que você passou a ter ao atingir essa idade.',
            'Relate uma atividade recente que comprove que você é um membro ativo do Clube.',
            'Explique uma forma concreta de melhorar sua participação no Clube.',
            'Diga como ajudar outro desbravador a cumprir esse mesmo requisito.',
            'Conte uma situação real em que você tentou viver o Voto do Desbravador.',
            'Diga qual item da Lei do Desbravador você decidiu melhorar a partir de agora.',
            'Conte a parte do livro do Clube de Leitura que mais te marcou.',
            'Explique uma lição do livro do Clube de Leitura que você pode aplicar no dia a dia.',
            'Diga por que esse livro foi escolhido como leitura do Clube.',
            'Conte uma história ou exemplo do livro Vaso de Barro que você lembra bem.',
            'Explique o que o livro Vaso de Barro ensina sobre como Deus trabalha na vida das pessoas.',
            'Diga uma mudança de atitude que o livro Vaso de Barro te inspirou a fazer.',
            'Conte uma história bíblica que você aprendeu na classe bíblica do Clube.',
            'Explique uma atitude que demonstra participação ativa na classe bíblica.',
            'Diga um hábito que pode melhorar ainda mais seu estudo da Bíblia.',
            'Escolha um dia da Criação e explique detalhadamente o que Deus criou nesse dia.',
            'Diga qual dia da Criação mais te chama atenção e por quê.',
            'Explique como o relato da Criação ensina o desbravador a cuidar da natureza.',
            'Escolha uma das dez pragas do Egito e explique o que aconteceu.',
            'Explique o que essa história ensina sobre o poder de Deus.',
            'Diga uma lição prática que podemos aprender com as pragas do Egito.',
            'Explique a origem de uma das tribos de Israel.',
            'Diga uma lição que essa organização do povo traz para os dias de hoje.',
            'Explique por que a união entre as tribos era importante.',
            'Encontre rapidamente, na Bíblia, um livro do Antigo Testamento solicitado pelo avaliador.',
            'Explique como localizar um livro, capítulo e versículo na Bíblia.',
            'Diga qual livro do Antigo Testamento você mais gostou de estudar e por quê.',
            'Escolha um dos versos bíblicos estudados e explique com suas próprias palavras.',
            'Diga como um desses versos pode ser aplicado na vida diária do desbravador.',
            'Explique por que memorizar versos bíblicos é importante.',
            'Conte uma história lida em Gênesis ou Êxodo que mais te marcou.',
            'Explique uma lição prática aprendida com essa leitura bíblica.',
            'Diga como a leitura da Bíblia pode ajudar nas decisões do dia a dia.',
            'Conte detalhadamente como foi uma das ações de serviço comunitário que você realizou.',
            'Explique como essa experiência de serviço ajudou você a entender melhor o cuidado com o próximo.',
            'Diga de que forma você poderia repetir ou ampliar esse tipo de serviço no futuro.',
            'Explique oralmente um dos pontos principais que você escreveu na redação sobre cidadania.',
            'Cite uma atitude prática que você já realiza no lar ou na escola que demonstre boa cidadania.',
            'Diga uma atitude que você ainda pode melhorar para viver melhor o que escreveu.',
            'Conte uma situação real em que você praticou a Regra Áurea no seu dia a dia.',
            'Explique como você pode ser um amigo melhor dentro do Clube de Desbravadores.',
            'Diga como resolver um conflito entre amigos de forma correta.',
            'Cante ou recite corretamente um trecho do Hino Nacional do Brasil.',
            'Explique, com suas palavras, o significado do Hino Nacional.',
            'Diga por que respeitar os símbolos nacionais é importante.',
            'Explique, passo a passo, uma atividade prática aprendida na especialidade de Saúde e Aptidão Física.',
            'Conte uma dificuldade que você teve ao realizar essa especialidade e como superou.',
            'Diga como você pode usar esse aprendizado para ajudar outras pessoas.',
            'Conte como foi sua participação em uma apresentação, encenação ou explicação sobre Daniel 1.',
            'Recite Daniel 1:8 e explique o que esse verso ensina para sua vida.',
            'Leia seu compromisso pessoal de seguir um estilo de vida saudável e explique por que o escreveu.',
            'Explique como você ajudou a preparar o quadro com os grupos básicos de alimentos.',
            'Dê um exemplo de refeição saudável usando diferentes grupos de alimentos.',
            'Diga uma mudança positiva que você pode fazer na sua alimentação.',
            'Conte como foi a caminhada de 5 km que você acompanhou.',
            'Diga o que você faria se fosse o líder dessa caminhada.',
            'Explique um cuidado importante que deve ser observado em caminhadas.',
            'Explique um conteúdo prático aprendido na especialidade de Estudo da Natureza.',
            'Conte como foi sua experiência ao realizar essa especialidade.',
            'Diga como você pode aplicar esse aprendizado no seu dia a dia.',
            'Explique e demonstre verbalmente uma maneira de purificar a água aprendida neste requisito.',
            'Explique, com suas palavras, sobre Jesus como sendo a Água da Vida.',
            'Conte como esse ensinamento pode ser aplicado à sua vida espiritual.',
            'Explique o passo a passo da montagem de um dos tipos de barraca aprendidos.',
            'Conte como foi sua experiência ao montar três tipos diferentes de barracas.',
            'Diga quais cuidados você teria ao escolher um local para montar uma barraca.',
            'Explique o uso prático de três dos nós aprendidos neste requisito de Arte de Acampar.',
            'Conte como você aprendeu a fazer os nós exigidos e quais achou mais difíceis.',
            'Diga em que situações reais de acampamento você utilizaria os nós aprendidos.',
            'Conte como foi sua experiência ao completar a especialidade de Acampamento I.',
            'Explique uma prática essencial de acampamento aprendida nessa especialidade.',
            'Diga como você ajudaria alguém que nunca participou de um acampamento.',
            'Explique, com suas palavras, o que fazer ao se perder em uma caminhada.',
            'Conte uma situação em que regras de caminhada ajudaram a evitar problemas.',
            'Diga como você orientaria um colega que se perdeu durante uma trilha.',
            'Explique como você preparou uma pista com pelo menos dez sinais.',
            'Conte como foi seguir uma pista preparada por outra pessoa.',
            'Diga quais cuidados você teria para garantir que outras pessoas consigam seguir sua pista corretamente.',
            'Descreva passo a passo uma técnica específica aprendida na especialidade de Artes e Habilidades Manuais.',
            'Conte como foi o processo de criação de um trabalho, objeto ou projeto dessa especialidade.',
            'Explique como você ensinaria essa habilidade manual para outra pessoa.',
        ]
    },
    // Estrutura preparada para futuras categorias
    'amigo-natureza': { name: 'Amigo da Natureza', displayName: 'Classe Amigo da Natureza', verdades: [], desafios: [] },
    'companheiro': { name: 'Companheiro', displayName: 'Classe Companheiro', verdades: [], desafios: [] },
    'companheiro-excursionismo': { name: 'Comp. Excursionismo', displayName: 'Classe Companheiro de Excursionismo', verdades: [], desafios: [] },
    'pesquisador': { name: 'Pesquisador', displayName: 'Classe Pesquisador', verdades: [], desafios: [] },
    'pesquisador-campo': { name: 'Pesq. Campo e Bosque', displayName: 'Classe Pesquisador de Campo e Bosque', verdades: [], desafios: [] },
    'pioneiro': { name: 'Pioneiro', displayName: 'Classe Pioneiro', verdades: [], desafios: [] },
    'pioneiro-fronteiras': { name: 'Pioneiro Fronteiras', displayName: 'Classe Pioneiro de Novas Fronteiras', verdades: [], desafios: [] },
    'excursionista': { name: 'Excursionista', displayName: 'Classe Excursionista', verdades: [], desafios: [] },
    'excursionista-mata': { name: 'Excursionista Mata', displayName: 'Classe Excursionista na Mata', verdades: [], desafios: [] },
    'guia': { name: 'Guia', displayName: 'Classe Guia', verdades: [], desafios: [] },
    'guia-exploracao': { name: 'Guia Exploração', displayName: 'Classe Guia de Exploração', verdades: [], desafios: [] },
};
